#!/bin/sh
# Author: Jonas Schubert <guepardoapps@gmail.com>
# Version: 1.6.0.161204
# Date: 04.12.2016

. /lib/lsb/init-functions

do_start()
{
	echo "Starting lucahome server: "
	/bin/lucahome &
  	log_success_msg "done"
	return 0
}

do_stop()
{
	echo  "Stopping lucahome server: "
	pkill lucahome > /dev/null
	log_success_msg "done"
	return 0
}

### main logic ###
case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        status lucahome
        ;;
  restart|reload|condrestart)
        do_stop
        do_start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
