/***********************************************/
/*************** USER DEFINITIONS **************/
/***********************************************/

#define DEFAULT_PASSWORD "0000"
#define MAX_INVALID_LOGIN_COUNT 5
#define NO_PASSWORD "NO_PASSWORD"
#define DUMMY "DUMMY"
#define SCHEDULER "Scheduler"
#define SCHEDULER_PASSWORD "435435"

/***********************************************/
/************* SUCCESS DEFINITIONS *************/
/***********************************************/

#define AUTHENTIFICATION_RESET_FAILED_LOGIN_COUNT_SUCCESS "AUTHENTIFICATION:RESET_FAILED_LOGIN_COUNT:SUCCESS"

#define BIRTHDAY_ADD_SUCCESS "BIRTHDAY:ADD:SUCCESS"
#define BIRTHDAY_UPDATE_SUCCESS "BIRTHDAY:UPDATE:SUCCESS"
#define BIRTHDAY_DELETE_SUCCESS "BIRTHDAY:DELETE:SUCCESS"
#define BIRTHDAY_ACTIVATE_CONTROL_SUCCESS "BIRTHDAY:SET_CONTROL_ON:SUCCESS"
#define BIRTHDAY_DEACTIVATE_CONTROL_SUCCESS "BIRTHDAY:SET_CONTROL_OFF:SUCCESS"

#define CAMERA_START_CAMERA_SUCCESS "CAMERA:START_CAMERA:SUCCESS"
#define CAMERA_STOP_CAMERA_SUCCESS "CAMERA:STOP_CAMERA:SUCCESS"
#define CAMERA_START_MOTION_SUCCESS "CAMERA:START_MOTION:SUCCESS"
#define CAMERA_STOP_MOTION_SUCCESS "CAMERA:STOP_MOTION:SUCCESS"
#define CAMERA_ACTIVATE_MOTION_CONTROL_SUCCESS "CAMERA:SET_MOTION_CONTROL_ON:SUCCESS"
#define CAMERA_DEACTIVATE_MOTION_CONTROL_SUCCESS "CAMERA:SET_MOTION_CONTROL_OFF:SUCCESS"

#define COIN_ADD_SUCCESS "COIN:ADD:SUCCESS"
#define COIN_UPDATE_SUCCESS "COIN:UPDATE:SUCCESS"
#define COIN_DELETE_SUCCESS "COIN:DELETE:SUCCESS"

#define COMMAND_RELOAD_SUCCESS "COMMAND:RELOAD:SUCCESS"

#define MAP_CONTENT_ADD_SUCCESS "MAP_CONTENT:ADD:SUCCESS"
#define MAP_CONTENT_UPDATE_SUCCESS "MAP_CONTENT:UPDATE:SUCCESS"
#define MAP_CONTENT_DELETE_SUCCESS "MAP_CONTENT:DELETE:SUCCESS"

#define MEAL_UPDATE_SUCCESS "MEAL:UPDATE:SUCCESS"
#define MEAL_CLEAR_SUCCESS "MEAL:CLEAR:SUCCESS"

#define MEDIA_SERVER_ADD_SUCCESS "MEDIA_SERVER:ADD:SUCCESS"
#define MEDIA_SERVER_UPDATE_SUCCESS "MEDIA_SERVER:UPDATE:SUCCESS"
#define MEDIA_SERVER_DELETE_SUCCESS "MEDIA_SERVER:DELETE:SUCCESS"

#define METER_LOG_ITEM_ADD_SUCCESS "METER_LOG_ITEM:ADD:SUCCESS"
#define METER_LOG_ITEM_UPDATE_SUCCESS "METER_LOG_ITEM:UPDATE:SUCCESS"
#define METER_LOG_ITEM_DELETE_SUCCESS "METER_LOG_ITEM:DELETE:SUCCESS"

#define MONEY_LOG_ITEM_ADD_SUCCESS "MONEY_LOG_ITEM:ADD:SUCCESS"
#define MONEY_LOG_ITEM_UPDATE_SUCCESS "MONEY_LOG_ITEM:UPDATE:SUCCESS"
#define MONEY_LOG_ITEM_DELETE_SUCCESS "MONEY_LOG_ITEM:DELETE:SUCCESS"

#define MOVIE_UPDATE_SUCCESS "MOVIE:UPDATE:SUCCESS"
#define MOVIE_LOAD_SUCCESS "MOVIE:LOAD:SUCCESS"

#define PUCKJS_ADD_SUCCESS "PUCKJS:ADD:SUCCESS"
#define PUCKJS_UPDATE_SUCCESS "PUCKJS:UPDATE:SUCCESS"
#define PUCKJS_DELETE_SUCCESS "PUCKJS:DELETE:SUCCESS"

#define RADIO_STREAM_ADD_SUCCESS "RADIO_STREAM:ADD:SUCCESS"
#define RADIO_STREAM_UPDATE_SUCCESS "RADIO_STREAM:UPDATE:SUCCESS"
#define RADIO_STREAM_DELETE_SUCCESS "RADIO_STREAM:DELETE:SUCCESS"

#define ROOM_ADD_SUCCESS "ROOM:ADD:SUCCESS"
#define ROOM_UPDATE_SUCCESS "ROOM:UPDATE:SUCCESS"
#define ROOM_DELETE_SUCCESS "ROOM:DELETE:SUCCESS"

#define RSS_FEED_ADD_SUCCESS "RSS_FEED:ADD:SUCCESS"
#define RSS_FEED_UPDATE_SUCCESS "RSS_FEED:UPDATE:SUCCESS"
#define RSS_FEED_DELETE_SUCCESS "RSS_FEED:DELETE:SUCCESS"

#define SHOPPING_ITEM_ADD_SUCCESS "SHOPPING_ITEM:ADD:SUCCESS"
#define SHOPPING_ITEM_UPDATE_SUCCESS "SHOPPING_ITEM:UPDATE:SUCCESS"
#define SHOPPING_ITEM_DELETE_SUCCESS "SHOPPING_ITEM:DELETE:SUCCESS"

#define SUGGESTED_MEAL_ADD_SUCCESS "SUGGESTED_MEAL:ADD:SUCCESS"
#define SUGGESTED_MEAL_UPDATE_SUCCESS "SUGGESTED_MEAL:UPDATE:SUCCESS"
#define SUGGESTED_MEAL_DELETE_SUCCESS "SUGGESTED_MEAL:DELETE:SUCCESS"

#define SUGGESTED_SHOPPING_ITEM_ADD_SUCCESS "SUGGESTED_SHOPPING_ITEM:ADD:SUCCESS"
#define SUGGESTED_SHOPPING_ITEM_UPDATE_SUCCESS "SUGGESTED_SHOPPING_ITEM:UPDATE:SUCCESS"
#define SUGGESTED_SHOPPING_ITEM_DELETE_SUCCESS "SUGGESTED_SHOPPING_ITEM:DELETE:SUCCESS"

#define TEMPERATURE_ACTIVATE_CONTROL_SUCCESS "TEMPERATURE:SET_CONTROL_ON:SUCCESS"
#define TEMPERATURE_DEACTIVATE_CONTROL_SUCCESS "TEMPERATURE:SET_CONTROL_OFF:SUCCESS"

#define USER_VALIDATE_SUCCESS "USER:VALIDATE:SUCCESS"
#define USER_ADD_SUCCESS "USER:ADD:SUCCESS"
#define USER_UPDATE_SUCCESS "USER:UPDATE:SUCCESS"
#define USER_DELETE_SUCCESS "USER:DELETE:SUCCESS"

#define WIRELESS_SCHEDULE_ADD_SUCCESS "WIRELESS_SCHEDULE:ADD:SUCCESS"
#define WIRELESS_SCHEDULE_UPDATE_SUCCESS "WIRELESS_SCHEDULE:UPDATE:SUCCESS"
#define WIRELESS_SCHEDULE_DELETE_SUCCESS "WIRELESS_SCHEDULE:DELETE:SUCCESS"
#define WIRELESS_SCHEDULE_ACTIVATE_ALL_SUCCESS "WIRELESS_SCHEDULE:ACTIVATE_ALL:SUCCESS"
#define WIRELESS_SCHEDULE_DEACTIVATE_ALL_SUCCESS "WIRELESS_SCHEDULE:DEACTIVATE_ALL:SUCCESS"
#define WIRELESS_SCHEDULE_SET_SUCCESS "WIRELESS_SCHEDULE:SET:SUCCESS"

#define WIRELESS_SOCKET_ADD_SUCCESS "WIRELESS_SOCKET:ADD:SUCCESS"
#define WIRELESS_SOCKET_UPDATE_SUCCESS "WIRELESS_SOCKET:UPDATE:SUCCESS"
#define WIRELESS_SOCKET_DELETE_SUCCESS "WIRELESS_SOCKET:DELETE:SUCCESS"
#define WIRELESS_SOCKET_ACTIVATE_ALL_SUCCESS "WIRELESS_SOCKET:ACTIVATE_ALL:SUCCESS"
#define WIRELESS_SOCKET_DEACTIVATE_ALL_SUCCESS "WIRELESS_SOCKET:DEACTIVATE_ALL:SUCCESS"
#define WIRELESS_SOCKET_SET_SUCCESS "WIRELESS_SOCKET:SET:SUCCESS"

#define WIRELESS_SWITCH_ADD_SUCCESS "WIRELESS_SWITCH:ADD:SUCCESS"
#define WIRELESS_SWITCH_UPDATE_SUCCESS "WIRELESS_SWITCH:UPDATE:SUCCESS"
#define WIRELESS_SWITCH_DELETE_SUCCESS "WIRELESS_SWITCH:DELETE:SUCCESS"
#define WIRELESS_SWITCH_TOGGLE_ALL_SUCCESS "WIRELESS_SWITCH:TOGGLE_ALL:SUCCESS"
#define WIRELESS_SWITCH_TOGGLE_SUCCESS "WIRELESS_SOCKET:TOGGLE:SUCCESS"

#define YOUTUBE_VIDEO_ADD_SUCCESS "YOUTUBE_VIDEO:ADD:SUCCESS"
#define YOUTUBE_VIDEO_UPDATE_SUCCESS "YOUTUBE_VIDEO:UPDATE:SUCCESS"
#define YOUTUBE_VIDEO_DELETE_SUCCESS "YOUTUBE_VIDEO:DELETE:SUCCESS"

/***********************************************/
/************** ERROR DEFINITIONS **************/
/***********************************************/

#define AUTHENTIFICATION_ERROR_FAILED "Error 10:Authentification failed"
#define AUTHENTIFICATION_ERROR_NO_RIGHTS "Error 11:UserAction cannot be performed! No rights"
#define AUTHENTIFICATION_ERROR_NO_PASSWORD "Error 12:No password"
#define AUTHENTIFICATION_ERROR_NO_USERNAME "Error 13:No username"
#define AUTHENTIFICATION_ERROR_INVALID_SOURCE "Error 14:Invalid source"
#define AUTHENTIFICATION_ERROR_RESET_FAILED "Error 15:Could not reset invalid login count"
#define AUTHENTIFICATION_ERROR_NO_ADMIN "Error 16:Permitted! User is no admin!"

#define COMMAND_ERROR_NO_ACTION_FOUND "Error 20:action not found"
#define COMMAND_ERROR_NO_PARAMETER_FOUND "Error 21:parameter not found"
#define COMMAND_ERROR_SHORT_STATEMENT "Error 22:statement too short"
#define COMMAND_ERROR_NO_ACTION "Error 23:No action"
#define COMMAND_ERROR_NO_CATEGORY "Error 24:No category"
#define COMMAND_ERROR_NO_PARAMETER "Error 25:No action parameter"
#define COMMAND_ERROR_SCHEDULER_EXTERNAL_NOT_ALLOWED "Error 26:scheduler not allowed from external source"

#define BIRTHDAY_ERROR_ADD "Error 31:Failed to add birthday"
#define BIRTHDAY_ERROR_UPDATE "Error 32:Failed to update birthday"
#define BIRTHDAY_ERROR_DELETE "Error 33:Failed to delete birthday"
#define BIRTHDAY_ERROR_WRONG_WORD_SIZE "Error 34:Wrong word size for birthday"
#define BIRTHDAY_ERROR_INVALID_DATA "Error 39:Invalid data for birthday"

#define CAMERA_ERROR_MOTION_IS_RUNNING "Error 156:Camera motion already running"
#define CAMERA_ERROR_MOTION_NOT_RUNNING "Error 157:Camera motion not running"
#define CAMERA_ERROR_INVALID_INDEX_5_DATA "Error 158:Invalid data at index 5 for camera"
#define CAMERA_ERROR_INVALID_DATA "Error 159:Invalid data for camera"

#define COIN_ERROR_ADD "Error 171:Could not add coin"
#define COIN_ERROR_UPDATE "Error 172:Could not update coin"
#define COIN_ERROR_DELETE "Error 173:Could not delete coin"
#define COIN_ERROR_WRONG_WORD_SIZE "Error 174:Wrong word size for coin"

#define MAP_CONTENT_ERROR_ADD "Error 101:Could not add mapcontent"
#define MAP_CONTENT_ERROR_UPDATE "Error 102:Could not update mapcontent"
#define MAP_CONTENT_ERROR_DELETE "Error 103:Could not delete mapcontent"
#define MAP_CONTENT_ERROR_WRONG_WORD_SIZE "Error 104:Wrong word size for mapcontent"

#define MEAL_ERROR_UPDATE "Error 132:Could not update meal"
#define MEAL_ERROR_CLEAR "Error 133:Could not clear meal"
#define MEAL_ERROR_WRONG_WORD_SIZE "Error 134:Wrong word size for meal"
#define MEAL_ERROR_INVALID_DATA "Error 139:Invalid data for meal"

#define MEDIASERVER_ERROR_ADD "Error 211:Could not add mediaserver"
#define MEDIASERVER_ERROR_UPDATE "Error 212:Could not update mediaserver"
#define MEDIASERVER_ERROR_DELETE "Error 213:Could not delete mediaserver"
#define MEDIASERVER_ERROR_WRONG_WORD_SIZE "Error 214:Wrong word size for mediaserver"

#define METER_LOG_ITEM_ERROR_ADD "Error 161:Could not add meter log item"
#define METER_LOG_ITEM_ERROR_UPDATE "Error 162:Could not update meter log item"
#define METER_LOG_ITEM_ERROR_DELETE "Error 163:Could not delete meter log item"
#define METER_LOG_ITEM_ERROR_WRONG_WORD_SIZE "Error 164:Wrong word size for meter log item"
#define METER_LOG_ITEM_ERROR_INVALID_DATA "Error 169:Invalid data for meter log item"

#define MONEY_LOG_ITEM_ERROR_ADD "Error 181:Could not add money log item"
#define MONEY_LOG_ITEM_ERROR_UPDATE "Error 182:Could not update money log item"
#define MONEY_LOG_ITEM_ERROR_DELETE "Error 183:Could not delete money log item"
#define MONEY_LOG_ITEM_ERROR_WRONG_WORD_SIZE "Error 184:Wrong word size for money log item"
#define MONEY_LOG_ITEM_ERROR_INVALID_DATA "Error 189:Invalid data for money log item"

#define MOVIE_ERROR_UPDATE "Error 42:Could not update movie"
#define MOVIE_ERROR_WRONG_WORD_SIZE "Error 44:Wrong word size for movie"
#define MOVIE_ERROR_INVALID_INDEX "Error 49:Start index higher then last index value"

#define PUCKJS_ERROR_ADD "Error 191:Could not add puckjs"
#define PUCKJS_ERROR_UPDATE "Error 192:Could not update puckjs"
#define PUCKJS_ERROR_DELETE "Error 193:Could not delete puckjs"
#define PUCKJS_ERROR_WRONG_WORD_SIZE "Error 194:Wrong word size for puckjs"

#define RADIO_STREAM_ERROR_ADD "Error 231:Could not add radio stream"
#define RADIO_STREAM_ERROR_UPDATE "Error 232:Could not update radio stream"
#define RADIO_STREAM_ERROR_DELETE "Error 233:Could not delete radio stream"
#define RADIO_STREAM_ERROR_WRONG_WORD_SIZE "Error 234:Wrong word size for radio stream"

#define ROOM_ERROR_ADD "Error 201:Could not add room"
#define ROOM_ERROR_UPDATE "Error 202:Could not update room"
#define ROOM_ERROR_DELETE "Error 203:Could not delete room"
#define ROOM_ERROR_WRONG_WORD_SIZE "Error 204:Wrong word size for room"

#define RSS_FEED_ERROR_ADD "Error 241:Could not add rss feed"
#define RSS_FEED_ERROR_UPDATE "Error 242:Could not update rss feed"
#define RSS_FEED_ERROR_DELETE "Error 243:Could not delete rss feed"
#define RSS_FEED_ERROR_WRONG_WORD_SIZE "Error 244:Wrong word size for rss feed"

#define SHOPPING_ITEM_ERROR_ADD "Error 111:Could not add shopping item"
#define SHOPPING_ITEM_ERROR_UPDATE "Error 112:Could not update shopping item"
#define SHOPPING_ITEM_ERROR_DELETE "Error 113:Could not delete shopping item"
#define SHOPPING_ITEM_ERROR_WRONG_WORD_SIZE "Error 114:Wrong word size for shopping item"

#define SUGGESTED_MEAL_ERROR_ADD "Error 141:Could not add suggested meal"
#define SUGGESTED_MEAL_ERROR_UPDATE "Error 142:Could not update suggested meal"
#define SUGGESTED_MEAL_ERROR_DELETE "Error 143:Could not delete suggested meal"
#define SUGGESTED_MEAL_ERROR_WRONG_WORD_SIZE "Error 144:Wrong word size for suggested meal"

#define SUGGESTED_SHOPPING_ITEM_ERROR_ADD "Error 121:Could not add suggested shopping item"
#define SUGGESTED_SHOPPING_ITEM_ERROR_UPDATE "Error 122:Could not update suggested shopping item"
#define SUGGESTED_SHOPPING_ITEM_ERROR_DELETE "Error 123:Could not delete suggested shopping item"
#define SUGGESTED_SHOPPING_ITEM_ERROR_WRONG_WORD_SIZE "Error 124:Wrong word size for suggested shopping item"

#define TEMPERATURE_ERROR_INVALID_DATA "Error 99:Invalid data for temperature"

#define USER_ERROR_ADD "Error 251:Could not add user"
#define USER_ERROR_UPDATE "Error 252:Could not update user"
#define USER_ERROR_DELETE "Error 253:Could not delete user"
#define USER_ERROR_WRONG_WORD_SIZE "Error 254:Wrong word size for user"

#define WIRELESS_SCHEDULE_ERROR_SET "Error 60:Could not set wireless schedule"
#define WIRELESS_SCHEDULE_ERROR_ADD "Error 61:Could not add wireless schedule"
#define WIRELESS_SCHEDULE_ERROR_UPDATE "Error 62:Could not update wireless schedule"
#define WIRELESS_SCHEDULE_ERROR_DELETE "Error 63:Could not delete wireless schedule"
#define WIRELESS_SCHEDULE_ERROR_WRONG_WORD_SIZE "Error 64:Wrong word size for wireless schedule"
#define WIRELESS_SCHEDULE_ERROR_INVALID_STATE "Error 69:Invalid state for wireless schedule"

#define WIRELESS_SOCKET_ERROR_SET "Error 70:Could not set wireless socket"
#define WIRELESS_SOCKET_ERROR_ADD "Error 71:Could not add wireless socket"
#define WIRELESS_SOCKET_ERROR_UPDATE "Error 72:Could not update wireless socket"
#define WIRELESS_SOCKET_ERROR_DELETE "Error 73:Could not delete wireless socket"
#define WIRELESS_SOCKET_ERROR_WRONG_WORD_SIZE "Error 74:Wrong word size for wireless socket"
#define WIRELESS_SOCKET_ERROR_INVALID_STATE "Error 79:Invalid state for wireless socket"

#define WIRELESS_SWITCH_ERROR_TOGGLE "Error 80:Could not toggle wireless switch"
#define WIRELESS_SWITCH_ERROR_ADD "Error 81:Could not add wireless switch"
#define WIRELESS_SWITCH_ERROR_UPDATE "Error 82:Could not update wireless switch"
#define WIRELESS_SWITCH_ERROR_DELETE "Error 83:Could not delete wireless switch"
#define WIRELESS_SWITCH_ERROR_WRONG_WORD_SIZE "Error 84:Wrong word size for wireless switch"

#define YOUTUBE_VIDEO_ITEM_ERROR_ADD "Error 221:Could not add youtube video"
#define YOUTUBE_VIDEO_ITEM_ERROR_UPDATE "Error 222:Could not update youtube video"
#define YOUTUBE_VIDEO_ITEM_ERROR_DELETE "Error 223:Could not delete youtube video"
#define YOUTUBE_VIDEO_ITEM_ERROR_WRONG_WORD_SIZE "Error 224:Wrong word size for youtube video"

/***********************************************/
/************* COMMAND DEFINITIONS *************/
/***********************************************/

#define ACTIVATE "ACTIVATE"
#define DEACTIVATE "DEACTIVATE"
#define TOGGLE "TOGGLE"

#define SET "SET"
#define ADD "ADD"
#define CLEAR "CLEAR"
#define DELETE "DELETE"
#define UPDATE "UPDATE"

#define ON "ON"
#define OFF "OFF"
#define ACTIVE "ACTIVE"
#define INACTIVE "INACTIVE"

#define ALL "ALL"
#define FOR_USER "FOR_USER"

#define AVAILABILITY "AVAILABILITY"
#define CHECK "CHECK"
#define CONTROL "CONTROL"
#define COUNT "COUNT"
#define DATA "DATA"
#define GET "GET"
#define INDEX "INDEX"
#define LOAD "LOAD"
#define MAIN "MAIN"
#define MOTION "MOTION"
#define PHP "PHP"
#define PLAY "PLAY"
#define RELOAD "RELOAD"
#define RESETFAILEDLOGIN "RESETFAILEDLOGIN"
#define SENSOR "SENSOR"
#define SETCONTROLTASK "SETCONTROLTASK"
#define START "START"
#define STATE "STATE"
#define STOP "STOP"
#define URL "URL"
#define VALIDATE "VALIDATE"

#define CAMERA_EVENTS_MAX_COUNT 25
#define CAMERA_IMAGES_TO_SEND 10

#define MAIL_MAX_MESSAGE_LENGTH 2048

#define BIRTHDAY "BIRTHDAY"
#define CAMERA "CAMERA"
#define CHANGE "CHANGE"
#define COIN "COIN"
#define INFORMATION "INFORMATION"
#define MAPCONTENT "MAPCONTENT"
#define MEAL "MEAL"
#define MEDIASERVER "MEDIASERVER"
#define METERLOGITEM "METERLOGITEM"
#define MONEYLOGITEM "MONEYLOGITEM"
#define MOVIE "MOVIE"
#define PUCKJS "PUCKJS"
#define RADIOSTREAM "RADIOSTREAM"
#define ROOM "ROOM"
#define RSSFEED "RSSFEED"
#define SHOPPINGITEM "SHOPPINGITEM"
#define SUGGESTEDMEAL "SUGGESTEDMEAL"
#define SUGGESTEDSHOPPINGITEM "SUGGESTEDSHOPPINGITEM"
#define TEMPERATURE "TEMPERATURE"
#define USER "USER"
#define WIRELESSSCHEDULE "WIRELESSSCHEDULE"
#define WIRELESSSOCKET "WIRELESSSOCKET"
#define WIRELESSSWITCH "WIRELESSSWITCH"
#define YOUTUBEVIDEO "YOUTUBEVIDEO"

#define ACTION_LEVEL_ERROR -1
#define ACTION_LEVEL_LOW 1
#define ACTION_LEVEL_MEDIUM 2
#define ACTION_LEVEL_NORMAL 3
#define ACTION_LEVEL_CRIT 4
#define ACTION_LEVEL_SYSTEM 5

#define CMD_MIN_LENGTH 25
#define CMD_MAX_LENGTH 4096
#define CMD_SOURCE_EXTERNAL 1
#define CMD_SOURCE_SCHEDULER 2

#define CMD_SUDO_MOTION "sudo motion"
#define CMD_SUDO_KILLALL_MOTION "sudo killall motion"
#define CMD_SUDO_REBOOT "sudo shutdown -r now"
#define CMD_SUDO_SHUTDOWN "sudo shutdown -h now"

#define CMD_SEND_SIMPLE_MAIL "python /etc/default/lucahome/mail.py"
#define CMD_SEND_IMAGE_MAIL "python /etc/default/lucahome/mailWithImage.py"

/***********************************************/
/************** INDEX DEFINITIONS **************/
/***********************************************/

#define USER_NAME_INDEX 0
#define PASSWORD_INDEX 1
#define CATEGORY_INDEX 2
#define ACTION_INDEX 3
#define ACTION_PARAMETER_INDEX 4

#define BIRTHDAY_UUID_INDEX 4
#define BIRTHDAY_NAME_INDEX 5
#define BIRTHDAY_DAY_INDEX 6
#define BIRTHDAY_MONTH_INDEX 7
#define BIRTHDAY_YEAR_INDEX 8
#define BIRTHDAY_GROUP_INDEX 9
#define BIRTHDAY_REMINDME_INDEX 10
#define BIRTHDAY_DATA_SIZE 11

#define CAMERA_CMD_PARAMETER_INDEX 5
#define CAMERA_DATA_SIZE 6

#define CHANGE_DATA_SIZE 5

#define COIN_UUID_INDEX 4
#define COIN_USER_INDEX 5
#define COIN_TYPE_INDEX 6
#define COIN_AMOUNT_INDEX 7
#define COIN_DATA_SIZE 8

#define MAP_CONTENT_UUID_INDEX 4
#define MAP_CONTENT_TYPE_UUID_INDEX 5
#define MAP_CONTENT_TYPE_INDEX 6
#define MAP_CONTENT_COORDINATES_INDEX 7
#define MAP_CONTENT_COORDINATES_X_INDEX 0
#define MAP_CONTENT_COORDINATES_Y_INDEX 1
#define MAP_CONTENT_NAME_INDEX 8
#define MAP_CONTENT_SHORT_NAME_INDEX 9
#define MAP_CONTENT_VISIBILITY_INDEX 10
#define MAP_CONTENT_DATA_SIZE 11

#define MEAL_UUID_INDEX 4
#define MEAL_TITLE_INDEX 5
#define MEAL_DESCRIPTION_INDEX 6
#define MEAL_WEEKDAY_INDEX 7
#define MEAL_DAY_INDEX 8
#define MEAL_MONTH_INDEX 9
#define MEAL_YEAR_INDEX 10
#define SUGGESTED_MEAL_SHOPPING_UUID_LIST_INDEX 11
#define MEAL_DATA_SIZE 12

#define MEDIASERVER_UUID_INDEX 4
#define MEDIASERVER_ROOM_UUID_INDEX 5
#define MEDIASERVER_IP_INDEX 6
#define MEDIASERVER_IS_SLEEPING_SERVER_INDEX 7
#define MEDIASERVER_WIRELESS_SOCKET_UUID 8
#define MEDIASERVER_DATA_SIZE 9

#define METER_LOG_ITEM_UUID_INDEX 4
#define METER_LOG_ITEM_ROOM_UUID_INDEX 5
#define METER_LOG_ITEM_TYPE_UUID_INDEX 6
#define METER_LOG_ITEM_TYPE_INDEX 7
#define METER_LOG_ITEM_DAY_INDEX 8
#define METER_LOG_ITEM_MONTH_INDEX 9
#define METER_LOG_ITEM_YEAR_INDEX 10
#define METER_LOG_ITEM_HOUR_INDEX 11
#define METER_LOG_ITEM_MINUTE_INDEX 12
#define METER_LOG_ITEM_METER_ID_INDEX 13
#define METER_LOG_ITEM_VALUE_INDEX 14
#define METER_LOG_ITEM_IMAGE_NAME_INDEX 15
#define METER_LOG_ITEM_DATA_SIZE 16

#define MONEY_LOG_ITEM_UUID_INDEX 4
#define MONEY_LOG_ITEM_TYPE_UUID_INDEX 5
#define MONEY_LOG_ITEM_BANK_INDEX 6
#define MONEY_LOG_ITEM_PLAN_INDEX 7
#define MONEY_LOG_ITEM_AMOUNT_INDEX 8
#define MONEY_LOG_ITEM_UNIT_INDEX 9
#define MONEY_LOG_ITEM_DAY_INDEX 10
#define MONEY_LOG_ITEM_MONTH_INDEX 11
#define MONEY_LOG_ITEM_YEAR_INDEX 12
#define MONEY_LOG_ITEM_USER_INDEX 13
#define MONEY_LOG_ITEM_DATA_SIZE 14

#define MOVIE_UUID_INDEX 4
#define MOVIE_TITLE_INDEX 5
#define MOVIE_GENRE_INDEX 6
#define MOVIE_DESCRIPTION_INDEX 7
#define MOVIE_RATING_INDEX 8
#define MOVIE_WATCH_COUNT_INDEX 9
#define MOVIE_DATA_SIZE 10

#define MOVIE_LOW_INDEX 5
#define MOVIE_HIGH_INDEX 6
#define MOVIE_ADDITIONAL_INDEX 7
#define MOVIE_INDEX_DATA_SIZE 8

#define PUCKJS_UUID_INDEX 4
#define PUCKJS_ROOM_UUID_INDEX 5
#define PUCKJS_NAME_INDEX 6
#define PUCKJS_MAC_INDEX 7
#define PUCKJS_DATA_SIZE 8

#define RADIO_STREAM_UUID_INDEX 4
#define RADIO_STREAM_TITLE_INDEX 5
#define RADIO_STREAM_URL_INDEX 6
#define RADIO_STREAM_DATA_SIZE 7

#define ROOM_UUID_INDEX 4
#define ROOM_NAME_INDEX 5
#define ROOM_TYPE_INDEX 6
#define ROOM_DATA_SIZE 7

#define RSS_FEED_UUID_INDEX 4
#define RSS_FEED_TITLE_INDEX 5
#define RSS_FEED_URL_INDEX 6
#define RSS_FEED_DATA_SIZE 7

#define SHOPPING_ITEM_UUID_INDEX 4
#define SHOPPING_ITEM_NAME_INDEX 5
#define SHOPPING_ITEM_TYPE_INDEX 6
#define SHOPPING_ITEM_QUANTITY_INDEX 7
#define SHOPPING_ITEM_UNIT_INDEX 8
#define SHOPPING_ITEM_DATA_SIZE 9

#define SUGGESTED_MEAL_UUID_INDEX 4
#define SUGGESTED_MEAL_TITLE_INDEX 5
#define SUGGESTED_MEAL_DESCRIPTION_INDEX 6
#define SUGGESTED_MEAL_RATING_INDEX 7
#define SUGGESTED_MEAL_USE_COUNTER_INDEX 8
#define SUGGESTED_MEAL_SHOPPING_UUID_LIST_INDEX 9
#define SUGGESTED_MEAL_DATA_SIZE 10

#define SUGGESTED_SHOPPING_ITEM_UUID_INDEX 4
#define SUGGESTED_SHOPPING_ITEM_NAME_INDEX 5
#define SUGGESTED_SHOPPING_ITEM_TYPE_INDEX 6
#define SUGGESTED_SHOPPING_ITEM_QUANTITY_INDEX 7
#define SUGGESTED_SHOPPING_ITEM_UNIT_INDEX 8
#define SUGGESTED_SHOPPING_ITEM_DATA_SIZE 9

#define USER_UUID_INDEX 4
#define USER_NAME_INDEX 5
#define USER_PASSPHRASE_INDEX 6
#define USER_ROLE_INDEX 7
#define USER_IS_ADMIN_INDEX 8
#define USER_INVALID_LOGIN_COUNT_INDEX 9
#define USER_DATA_SIZE 10

#define WIRELESS_SCHEDULE_UUID_INDEX 4
#define WIRELESS_SCHEDULE_NAME_INDEX 5
#define WIRELESS_SCHEDULE_WEEKDAY_INDEX 6
#define WIRELESS_SCHEDULE_HOUR_INDEX 7
#define WIRELESS_SCHEDULE_MINUTE_INDEX 8
#define WIRELESS_SCHEDULE_IS_ACTIVE_INDEX 9
#define WIRELESS_SCHEDULE_IS_TIMER_INDEX 10
#define WIRELESS_SCHEDULE_WIRELESS_SOCKET_UUID_INDEX 11
#define WIRELESS_SCHEDULE_WIRELESS_SOCKET_ACTION_INDEX 12
#define WIRELESS_SCHEDULE_WIRELESS_SWITCH_UUID_INDEX 13
#define WIRELESS_SCHEDULE_DATA_SIZE 14

#define WIRELESS_SCHEDULE_SET_STATE_INDEX 5
#define WIRELESS_SCHEDULE_SET_DATA_SIZE 6

#define WIRELESS_SOCKET_UUID_INDEX 4
#define WIRELESS_SOCKET_ROOM_UUID_INDEX 5
#define WIRELESS_SOCKET_NAME_INDEX 6
#define WIRELESS_SOCKET_CODE_INDEX 7
#define WIRELESS_SOCKET_STATE_INDEX 8
#define WIRELESS_SOCKET_LAST_TRIGGER_DAY_INDEX 9
#define WIRELESS_SOCKET_LAST_TRIGGER_MONTH_INDEX 10
#define WIRELESS_SOCKET_LAST_TRIGGER_YEAR_INDEX 11
#define WIRELESS_SOCKET_LAST_TRIGGER_HOUR_INDEX 12
#define WIRELESS_SOCKET_LAST_TRIGGER_MINUTE_INDEX 13
#define WIRELESS_SOCKET_LAST_TRIGGER_USER_INDEX 14
#define WIRELESS_SOCKET_DATA_SIZE 15

#define WIRELESS_SOCKET_SET_STATE_INDEX 5
#define WIRELESS_SOCKET_SET_DATA_SIZE 6

#define WIRELESS_SWITCH_UUID_INDEX 4
#define WIRELESS_SWITCH_ROOM_UUID_INDEX 5
#define WIRELESS_SWITCH_NAME_INDEX 6
#define WIRELESS_SWITCH_REMOTE_ID_INDEX 7
#define WIRELESS_SWITCH_KEY_CODE_INDEX 8
#define WIRELESS_SOCKET_ACTION_INDEX 9
#define WIRELESS_SWITCH_LAST_TRIGGER_DAY_INDEX 10
#define WIRELESS_SWITCH_LAST_TRIGGER_MONTH_INDEX 11
#define WIRELESS_SWITCH_LAST_TRIGGER_YEAR_INDEX 12
#define WIRELESS_SWITCH_LAST_TRIGGER_HOUR_INDEX 13
#define WIRELESS_SWITCH_LAST_TRIGGER_MINUTE_INDEX 14
#define WIRELESS_SWITCH_LAST_TRIGGER_USER_INDEX 15
#define WIRELESS_SWITCH_DATA_SIZE 16

#define WIRELESS_SWITCH_SET_DATA_SIZE 5

#define YOUTUBE_VIDEO_UUID_INDEX 4
#define YOUTUBE_VIDEO_TITLE_INDEX 5
#define YOUTUBE_VIDEO_ID_INDEX 6
#define YOUTUBE_VIDEO_DATA_SIZE 7

/***********************************************/
/************** TIMEOUT DEFINITIONS ************/
/***********************************************/

#define BIRTHDAY_CHECK_TIMEOUT 2 * 60 * 60
#define MOTION_CONTROL_TIMEOUT 15
#define SCHEDULE_CONTROL_TIMEOUT 10
#define TEMPERATURE_CONTROL_TIMEOUT 60
#define RELOAD_TIMEOUT 30 * 60

/***********************************************/
/*************** PATH DEFINITIONS **************/
/***********************************************/

#define NAS_PATH_CAMERA "/mnt/NAS/Camera/"
#define NAS_PATH_LUCAHOME "/mnt/NAS/LucaHome/"
#define NAS_PATH_METER_LOG "/mnt/NAS/MeterLog/"
#define NAS_PATH_MOVIE "/mnt/NAS/Movies/"
#define NAS_PATH_MUSIC "/mnt/NAS/Music/"
#define NAS_PATH_SERIES "/mnt/NAS/Series/"

/***********************************************/
/**************** FILE DEFINITIONS *************/
/***********************************************/

#define IS_FOLDER 0x4
#define IS_FILE 0x8

#define JPG_ENDING ".jpg"
#define SWF_ENDING ".swf"

#define NFO_LUCA_FILE "NFO.luca"
